
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

array = np.arange(10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
import numpy as np

array = np.arange(9)

matrix = array.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [3]:
import numpy as np

array = np.arange(9)

matrix = array.reshape(3, 3)

element = matrix[1, 1]

print(element)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [7]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition = array1 + array2
print("Addition:", addition)

subtraction = array1 - array2
print("Subtraction:", subtraction)

multiplication = array1 * array2
print("Multiplication:", multiplication)

division = array1 / array2
print("Division:", division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [5]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

sum_array = np.sum(array)
mean_array = np.mean(array)
std_dev_array = np.std(array)

print("Sum:", sum_array)
print("Mean:", mean_array)
print("Standard Deviation:", std_dev_array)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [6]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [8]:
random_array = np.random.randint(0,100, size=(5,5))
random_array

array([[13, 27, 24, 56, 11],
       [ 7, 42, 20, 97, 21],
       [59, 73, 43, 38,  6],
       [37, 86, 90, 36, 34],
       [23,  6, 95, 94, 51]])

Replace all values in the sub-array with a specific value.


In [10]:
random_array_value = random_array[:,1:4] = 10
random_array

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [14]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
arr
arr[[1,3]]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [16]:
array = np.array([0,1,2])
array

#title

new_array = np.tile(array, (3,1))
new_array


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [22]:
array_1d = np.array([0,1,2])
array_1d +new_array



array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [27]:
random_array1 = np.random.randint(0,100, size=(3,3))
random_array1

array([[53, 79, 96],
       [51, 49, 74],
       [87, 62, 86]])

In [28]:
random_array2 = np.random.randint(0,100, size=(3,3))
random_array2

array([[13, 46, 88],
       [48, 42, 18],
       [19,  0, 35]])

In [29]:
# hstack  vstack

concatenated_horizontally = np.hstack((random_array1,random_array2))
concatenated_horizontally

array([[53, 79, 96, 13, 46, 88],
       [51, 49, 74, 48, 42, 18],
       [87, 62, 86, 19,  0, 35]])

In [31]:
# vstack  vstack

concatenated_vertically = np.vstack((random_array1,random_array2))
concatenated_vertically

array([[53, 79, 96],
       [51, 49, 74],
       [87, 62, 86],
       [13, 46, 88],
       [48, 42, 18],
       [19,  0, 35]])

In [32]:
# hsplit & vsplit

splitted_array = np.hsplit(concatenated_horizontally,2)
splitted_array

[array([[53, 79, 96],
        [51, 49, 74],
        [87, 62, 86]]),
 array([[13, 46, 88],
        [48, 42, 18],
        [19,  0, 35]])]

In [34]:
# vsplit

splitted_array = np.vsplit(concatenated_vertically,3)
splitted_array

[array([[53, 79, 96],
        [51, 49, 74]]),
 array([[87, 62, 86],
        [13, 46, 88]]),
 array([[48, 42, 18],
        [19,  0, 35]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [39]:
array = [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]

mode = None
max_count = 0

for num in array:
    count = array.count(num)
    if count > max_count:
        mode = num
        max_count = count

print("Mode of the array:", mode)

Mode of the array: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

